// <auto-generated />
using System;
using Basket.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasketAPI_Shop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230711002944_Migration20")]
    partial class Migration20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("ShoppingCart", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CouponApplied")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserName");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("ShoppingCartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShoppingCartUserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartUserName");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("ShoppingCartItem", b =>
                {
                    b.HasOne("ShoppingCart", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCartUserName");
                });

            modelBuilder.Entity("ShoppingCart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
